### PR TITLE
Feature 53 dev

### PR DESCRIPTION
**Pull request by FlyingBlueTurtle**
- Refactored all sources of SkillType with Track, and Bucket with Category
- SimpleReportModel is created and implemented.
- old services ,and controllers removed, and added for SRM 
- controller is linked to /srm to return all SRM and 
- /srm/{dateStart}/{dateEnd} returns all SRM within the search time, inclusively

### CODE REVIEW

**Review by erchiggins — CHANGES_REQUESTED** [review]
Please remove unused dependencies instead of commenting them out. 
Remove "this version has the Hibernate removed" from Javadocs. 
Let's keep the Swagger docs in the beans and controller. 
All instance variables should be camelCase. 
Screening bean should be using the java.time LocalDateTime in accordance with Java 8. Screening bean also does not need a separate trackId if it's got a ScheduledScreening. 
Keep the naming convention in SoftSkillViolation - softSkillViolationId. This should also be using the java.time LocalDateTime. 
Track bean is not completely converted over to SkillType, please pull the bean structure directly from the approved version in screening-admin-service. 
The Weight bean has some spacing issues.
FeignCategory has references to Bucket still. 
FeignQuestion has similar issues and the comments are incorrect. 
FeignWeight has references to Bucket and SkillType.
FullReportModel should be using java.time dates. 
Add Swagger to models. 
Delete dead code in ReportService instead of commenting it out. 
tester class does not follow Java code conventions and should be deleted.

**Comment by FlyingBlueTurtle** [comment]
✓Please remove unused dependencies instead of commenting them out.
✓Remove "this version has the Hibernate removed" from Javadocs.
XLet's keep the Swagger docs in the beans and controller.
✓All instance variables should be camelCase.
✓Screening bean should be using the java.time LocalDateTime in accordance with Java 8. Screening ✓bean also does not need a separate trackId if it's got a ScheduledScreening.
✓Keep the naming convention in SoftSkillViolation - softSkillViolationId. This should also be using the java.time LocalDateTime.
✓Track bean is not completely converted over to SkillType, please pull the bean structure directly from the approved version in screening-admin-service.
✓The Weight bean has some spacing issues.
✓FeignCategory has references to Bucket still.
✓FeignQuestion has similar issues and the comments are incorrect.
✓FeignWeight has references to Bucket and SkillType.
✓FullReportModel should be using java.time dates.
XAdd Swagger to models.
✓Delete dead code in ReportService instead of commenting it out.
50%tester class does not follow Java code conventions and should be deleted.

**Review by erchiggins — CHANGES_REQUESTED** [review]
Rename tests to be ReportsServiceTest and ReportsControllerTest
ReportsService should not have any references to Buckets.

**Comment by FlyingBlueTurtle** [comment]
Rename tests to be ReportsServiceTest and ReportsControllerTest
Both rename
ReportsService should not have any references to Buckets.
All references to Buckets are changed to category/categories

**Review by erchiggins — APPROVED** [review]

**Pull request merged**
